use_frameworks!

platform :ios, '9.0'

target 'sdk-ios_Example' do
  pod 'sdk-ios', :path => '../'

  target 'sdk-ios_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
